activitiesservice:
  image: slidewiki/activitiesservice:latest-dev
  restart: on-failure:5
  expose:
    - "80"
  external_links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=activitiesservice.experimental.slidewiki.org
    - LETSENCRYPT_HOST=activitiesservice.experimental.slidewiki.org
    - LETSENCRYPT_EMAIL=meissner@informatik.uni-leipzig.de
    - SERVICE_URL_DECK=https://deckservice.experimental.slidewiki.org
    - SERVICE_URL_NOTIFICATION=https://notificationservice.experimental.slidewiki.org
    - SERVICE_URL_USER=https://userservice.experimental.slidewiki.org
    - LRS_ENDPOINT=https://xapi.learninglocker.experimental.slidewiki.org/data/xAPI
    - LRS_PUBLIC_KEY=7317904fa8b6f7e93d1c59874e47c84001994304
    - LRS_SECRET=26921b133273173c141abf14a4ac8087ee481115
    - DATABASE_URL=mongodb # use a url or the name, defined in the docker-compose file
    - JWT_SERIAL=69aac7f95a9152cd4ae7667c80557c284e413d748cca4c5715b3f02020a5ae1b
